defaults:
  - model
  - training
  - render
  - env
  - algo/ppo
  - eval

hydra:
  run:
    dir: ../outputs/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

paths:
  video_dir: ../video
  log_dir: ../mlruns

experiment:
  name: ppo_mujoco_experiment
  run_name: run_baseline
